import { IUser } from '../models/user.model';

export const users: IUser[] = [
  {
    profilePhoto: 'https://randomuser.me/api/portraits/men/1.jpg',
    firstName: 'Ali',
    lastName: 'Karimi',
    age: 28,
    education: 'Bachelor of Computer Science',
    nationalID: 1234567890,
    birthdate: '1997-03-15',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/women/2.jpg',
    firstName: 'Sara',
    lastName: 'Ahmadi',
    age: 24,
    education: 'Master of Business Administration',
    nationalID: 2345678901,
    birthdate: '2001-07-09',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/men/3.jpg',
    firstName: 'Hossein',
    lastName: 'Rezai',
    age: 31,
    education: 'Bachelor of Mechanical Engineering',
    nationalID: 3456789012,
    birthdate: '1994-11-21',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/women/4.jpg',
    firstName: 'Narges',
    lastName: 'Shirazi',
    age: 27,
    education: 'PhD in Physics',
    nationalID: 4567890123,
    birthdate: '1998-02-10',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/men/5.jpg',
    firstName: 'Mohammad',
    lastName: 'Davoodi',
    age: 35,
    education: 'High School Diploma',
    nationalID: 5678901234,
    birthdate: '1989-06-30',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/women/6.jpg',
    firstName: 'Elham',
    lastName: 'Farhadi',
    age: 22,
    education: 'Bachelor of Arts',
    nationalID: 6789012345,
    birthdate: '2003-01-19',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/men/7.jpg',
    firstName: 'Reza',
    lastName: 'Najafi',
    age: 40,
    education: 'Master of Electrical Engineering',
    nationalID: 7890123456,
    birthdate: '1985-12-04',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/women/8.jpg',
    firstName: 'Mina',
    lastName: 'Khosravi',
    age: 26,
    education: 'Bachelor of Graphic Design',
    nationalID: 8901234567,
    birthdate: '1999-05-14',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/men/9.jpg',
    firstName: 'Saeed',
    lastName: 'Hosseini',
    age: 29,
    education: 'Bachelor of Civil Engineering',
    nationalID: 9012345678,
    birthdate: '1996-08-23',
  },
  {
    profilePhoto: 'https://randomuser.me/api/portraits/women/10.jpg',
    firstName: 'Parisa',
    lastName: 'Moradi',
    age: 33,
    education: 'Master of Psychology',
    nationalID: 1122334455,
    birthdate: '1992-09-17',
  },
];
